title: The Owl Path
email: owl@cephea.de
github: https://github.com/aengl/owlpath
description: >-
  The stories and adventures of two migrating owls.
baseurl: /owlpath
markdown: kramdown
plugins:
  - jekyll-feed
  - github-pages
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - package.json
  - yarn.lock
