title: The Owl Path
email: owl@cephea.de
description: >-
  The stories and adventures of two migrating owls.
baseurl: /owlpath
markdown: kramdown
plugins:
  - jekyll-feed
  - github-pages
exclude:
  - .chromium
  - .vscode
  - node_modules
  - scripts
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - yarn.lock
